services:
  mf_container:
    build:
      context: ./mf_container
      dockerfile: Dockerfile
    container_name: mf_container
    ports:
      - "3000:3000"

  mf_drawer:
    build:
      context: ./mf_drawer
      dockerfile: Dockerfile
    container_name: mf_drawer
    ports:
      - "3002:3002"

  mf_videos:
    build:
      context: ./mf_videos
      dockerfile: Dockerfile
    container_name: mf_videos
    ports:
      - "3001:3001"

  bff:
    build:
      context: ./bff
      dockerfile: Dockerfile
    container_name: bff
    ports:
      - "4000:4000"
