services:
  mf_container:
    build:
      context: ./mf_container
      dockerfile: Dockerfile
    container_name: mf_container
    ports:
      - "3000:3000"
    volumes:
      - ./mf_container:/app
    networks:
      - teste_2024

  mf_drawer:
    build:
      context: ./mf_drawer
      dockerfile: Dockerfile
    container_name: mf_drawer
    ports:
      - "3002:3002"
    volumes:
      - ./mf_drawer:/app
    networks:
      - teste_2024

  mf_videos:
    build:
      context: ./mf_videos
      dockerfile: Dockerfile
    container_name: mf_videos
    ports:
      - "3001:3001"
    volumes:
      - ./mf_videos:/app
    networks:
      - teste_2024

  bff:
    build:
      context: ./bff
      dockerfile: Dockerfile
    container_name: bff
    ports:
      - "4000:4000"
    volumes:
      - ./bff:/app
    networks:
      - teste_2024

networks:
  teste_2024:
    driver: bridge
